language: java

jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.m2

install: 
  - PATH=$TRAVIS_BUILD_DIR:$PATH
  - cp .travis.settings.xml $HOME/.m2/settings.xml
  - curl -fL https://getcli.jfrog.io | sh
  - chmod +x jfrog
  - jfrog rt config "cishell-artifactory" --url "https://cishell.jfrog.io/cishell/" --user $CI_DEPLOY_USERNAME --apikey $CI_DEPLOY_PASSWORD --interactive=false

script: 
  - mvn clean deploy &&
    cd $TRAVIS_BUILD_DIR/deployment/org.cishell.p2/target/repository &&
    jfrog rt delete "reference-gui/updates/*" --quiet &&
    jfrog rt upload "./*(.xml|.jar)" "reference-gui/updates/" --flat=false &&
    cd $TRAVIS_BUILD_DIR/deployment/org.cishell.reference.releng/target/products-final &&
    jfrog rt delete "reference-gui/latest/*" --quiet &&
    jfrog rt upload "./*" "reference-gui/latest/" --flat=false